version: '3.8'

services: 
    webserver:
        build: 
            context: ./webserver
            dockerfile: Dockerfile
        container_name: apache-php
        depends_on: 
            - db
        volumes: 
            - ./website:/var/www/html/
        ports: 
            - 8000:80
    
    db:
        image: mysql
        container_name: mysql
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mysql_database
          MYSQL_USER: mysql_user
          MYSQL_PASSWORD: password
        ports: 
            - 8080:3306

volumes:
    db_data: {}